# Generated by Django 4.2.2 on 2023-06-10 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_online', models.BooleanField(default=False)),
                ('profile_pic', models.ImageField(default='blank-profile-picture.png', upload_to='profile_pictures')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='YandexMusicTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_id', models.URLField(max_length=40, null=True, verbose_name='track url')),
                ('track_url', models.URLField(max_length=400, null=True, verbose_name='track url')),
                ('avatar_url', models.URLField(max_length=400, null=True, verbose_name='avatar')),
                ('explicit_state', models.CharField(max_length=10, null=True, verbose_name='explicit')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yandex_music_tracks', to='yandex_music_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='YandexMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_token', django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=200, null=True))),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yandex_token', to='yandex_music_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_track', models.IntegerField(blank=True, null=True)),
                ('tag_id', models.CharField(blank=True, max_length=30, null=True)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('track_type', models.CharField(blank=True, max_length=10, null=True)),
                ('track_type_id', models.CharField(blank=True, max_length=10, null=True)),
                ('stations_origin', models.CharField(blank=True, max_length=10, null=True)),
                ('station_id_for_from', models.CharField(blank=True, max_length=10, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_track', to='yandex_music_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_media_state', models.BooleanField(default=False)),
                ('stream_state', models.BooleanField(default=False)),
                ('followers_only', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='states', to='yandex_music_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RadioHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radio_history', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radio_history', to='yandex_music_app.profile')),
            ],
        ),
    ]
