# Generated by Django 4.2.2 on 2023-06-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banner_picture.jpg', upload_to='banner_pictures'),
        ),
        migrations.AddField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(blank=True, related_name='follower', to='yandex_music_app.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='thought',
            field=models.TextField(blank=True),
        ),
    ]
