# Generated by Django 4.2.2 on 2023-06-14 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0003_yandexmusic_language_alter_profile_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracks',
            name='sub_tag',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
