# Generated by Django 4.2.2 on 2023-06-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0004_tracks_sub_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='stream_state',
        ),
        migrations.RemoveField(
            model_name='yandexmusictracks',
            name='track_url',
        ),
        migrations.AddField(
            model_name='tracks',
            name='current_stations_origin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='radio_first_track',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tracks',
            name='radio_set',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='yandexmusictracks',
            name='last_added',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yandexmusictracks',
            name='track_artists',
            field=models.CharField(max_length=100, null=True, verbose_name='track_artists'),
        ),
        migrations.AddField(
            model_name='yandexmusictracks',
            name='track_name',
            field=models.CharField(max_length=100, null=True, verbose_name='track_name'),
        ),
        migrations.AlterField(
            model_name='yandexmusictracks',
            name='track_id',
            field=models.CharField(max_length=40, null=True, verbose_name='track_id'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('suffix', models.CharField(blank=True, max_length=10, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_link', to='yandex_music_app.profile')),
            ],
        ),
    ]
