# Generated by Django 4.2.2 on 2023-06-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0006_rename_radiohistory_radiohistorystate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banner.jpg', upload_to='banner_pictures'),
        ),
    ]
