# Generated by Django 4.2.2 on 2023-06-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0007_alter_profile_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_track',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='radio_first_track',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='radio_set',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='stations_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='sub_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='track_type_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
