# Generated by Django 4.2.2 on 2023-06-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0008_alter_media_name_alter_media_suffix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='current_stations_origin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='last_track',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='station_id_for_from',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
