# Generated by Django 4.2.2 on 2023-06-21 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_music_app', '0010_remove_state_local_media_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_online',
        ),
    ]
